# Generated by Django 5.2.6 on 2025-10-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_comment_parent_alter_comment_author_name'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionpreference',
            name='topics',
        ),
        migrations.AddField(
            model_name='subscriptionpreference',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='preferences', to='newsapp.category'),
        ),
    ]
